### ISSUE TITLE
NPE in plugin

### ISSUE THREAD

**Issue by stokito** [profeg/IntelliJGettersInspections#9]
```
null
java.lang.NullPointerException
    at com.github.profeg.IntelliJGettersCheckInspections.GetterUtils.methodBodyContainsOnlyReturnStatement(GetterUtils.java:15)
    at com.github.profeg.IntelliJGettersCheckInspections.GetterUtils.methodIsCanonicalGetter(GetterUtils.java:12)
    at com.github.profeg.IntelliJGettersCheckInspections.CanonicalGetterInspection$CanonicalGetterInspectionVisitor.checkForMethodWhichCanBeGetter(CanonicalGetterInspection.java:31)
    at com.github.profeg.IntelliJGettersCheckInspections.CanonicalGetterInspection$CanonicalGetterInspectionVisitor.visitClass(CanonicalGetterInspection.java:42)
    at com.intellij.psi.impl.source.PsiClassImpl.accept(PsiClassImpl.java:473)
    at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
    at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
    at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
    at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:122)
    at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
    at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
    at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
    at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:106)
    at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
    at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
    at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
    at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
    at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
    at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by profeg** [comment]
What action you perform for geting this error?

**Comment by stokito** [comment]
Just enabled it and this was thrown on some code. Can't tell you exactly :(
